// 前端：dasha 风格 UI — 导航 + 视图切换 + 聊天 + 模型 + 面板
// 2026-08-05: P0-P3 全面优化 + 完整面板渲染
const $ = (id) => document.getElementById(id);

let ws = null, busy = false;
let sessionId = localStorage.getItem('ah_session') || ('sess_' + Date.now());
let currentModelId = null, modelGroups = [], currentView = 'chat';
let activeAssistEl = null, activeActsEl = null, activeThoughtEl = null;
let pendingAttachments = [];

const chat = $('chat'), input = $('input'), sendBtn = $('sendBtn');

/* ─── 外部库检测 ─── */
const hasMarked = typeof marked !== 'undefined';
const hasHljs = typeof hljs !== 'undefined';
let _darkMode = localStorage.getItem('ah_dark') === '1';
function syncHljsTheme(dark) { const l = $('hljs-light'), d = $('hljs-dark'); if (l) l.disabled = dark; if (d) d.disabled = !dark; }

/* ─── 工具 ─── */
function escapeHtml(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function renderMarkdown(text) { if (!text) return ''; var e = escapeHtml(text); e = e.replace(/```(\w*)\n?([\s\S]*?)```/g, function(m, lang, code) { return '<pre><code>' + code.replace(/\n$/, '') + '</code></pre>'; }); e = e.replace(/`([^`\n]+)`/g, '<code>$1</code>'); e = e.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>'); return e; }
function renderMarkdownFull(text) { if (!text) return ''; if (hasMarked) { try { marked.setOptions({ breaks: true, gfm: true }); return marked.parse(text); } catch {} } return renderMarkdown(text); }

function enhanceCodeBlocks(container) { if (!container) return; var pres = container.querySelectorAll('pre'); for (var p = 0; p < pres.length; p++) { var pre = pres[p]; if (pre.parentElement && pre.parentElement.classList.contains('code-block-wrapper')) continue; var code = pre.querySelector('code'), lang = code ? (code.className.replace('language-', '') || '') : ''; var wrapper = document.createElement('div'); wrapper.className = 'code-block-wrapper'; if (lang) { var lt = document.createElement('div'); lt.className = 'code-lang'; lt.textContent = lang; wrapper.appendChild(lt); } var cbtn = document.createElement('button'); cbtn.className = 'copy-btn'; cbtn.textContent = '\u590d\u5236'; cbtn.onclick = function() { var txt = code ? code.textContent : pre.textContent || ''; navigator.clipboard.writeText(txt).then(function() { cbtn.textContent = '\u5df2\u590d\u5236'; cbtn.classList.add('copied'); setTimeout(function() { cbtn.textContent = '\u590d\u5236'; cbtn.classList.remove('copied'); }, 1500); }).catch(function() { var ta = document.createElement('textarea'); ta.value = txt; ta.style.cssText = 'position:fixed;left:-9999px'; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); document.body.removeChild(ta); cbtn.textContent = '\u5df2\u590d\u5236'; cbtn.classList.add('copied'); setTimeout(function() { cbtn.textContent = '\u590d\u5236'; cbtn.classList.remove('copied'); }, 1500); }); }; wrapper.appendChild(cbtn); pre.parentNode.insertBefore(wrapper, pre); wrapper.appendChild(pre); if (hasHljs && code) { try { hljs.highlightElement(code); } catch {} } } }
function fmtTime(ts) { if (!ts) return ''; return new Date(ts).toLocaleString('zh-CN', { hour12: false }); }
function fmtUptime(s) { s = Math.floor(s); var h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), sec = s % 60; return (h ? h + '\u5c0f\u65f6' : '') + m + '\u5206' + sec + '\u79d2'; }

/* ─── Toast (P2-5) ─── */
function showToast(msg, type) { type = type || ''; var c = $('toastContainer'); if (!c) return; var t = document.createElement('div'); t.className = 'toast toast-' + type; t.innerHTML = '<span>' + escapeHtml(msg) + '</span><button class="toast-close" aria-label="\u5173\u95ed">X</button>'; t.querySelector('.toast-close').onclick = function() { t.remove(); }; c.appendChild(t); setTimeout(function() { if (t.parentNode) t.remove(); }, 3000); }

/* ─── Token 用量 ─── */
var currentTokens = 0;
function estimateTokensJS(text) { if (!text) return 0; var cjk = 0, other = 0; for (var i = 0; i < text.length; i++) { var code = text.charCodeAt(i); if ((code >= 0x2e80 && code <= 0xfaff) || (code >= 0xff00 && code <= 0xffef) || (code >= 0x3000 && code <= 0x303f)) cjk++; else other++; } return Math.ceil(cjk + other / 4); }
var CTX_WARN = 4000, CTX_DANGER = 10000;
function updateCtxBadge(extraDraft) { extraDraft = extraDraft || 0; var el = $('ctxTokens'); if (!el) return; var total = currentTokens + extraDraft; el.textContent = '\u4e0a\u4e0b\u6587 ~' + total.toLocaleString() + ' tokens'; el.classList.toggle('warn', total >= CTX_WARN && total < CTX_DANGER); el.classList.toggle('danger', total >= CTX_DANGER); }
async function refreshTokens() { try { var d = await fetch('/api/sessions/' + encodeURIComponent(sessionId) + '/tokens').then(function(r) { return r.json(); }); currentTokens = d.tokens || 0; updateCtxBadge(0); } catch {} }
function updateInputTokens() { var el = $('tokenCounter'); if (!el) return; var n = estimateTokensJS(input.value); el.textContent = n.toLocaleString() + ' tokens'; el.classList.toggle('warn', n > 2000); el.classList.toggle('danger', n > 4000); }

/* ─── P1-3: 滚动优化 ─── */
var scrollRAF = null, _userScrolledUp = false;
function isNearBottom() { return chat.scrollHeight - chat.scrollTop - chat.clientHeight < 80; }
function scrollDown(force) { if (scrollRAF) return; scrollRAF = requestAnimationFrame(function() { scrollRAF = null; if (force || !_userScrolledUp || isNearBottom()) chat.scrollTop = chat.scrollHeight; var btn = $('scrollToBottomBtn'); if (btn) btn.hidden = isNearBottom(); }); }
chat.addEventListener('scroll', function() { _userScrolledUp = !isNearBottom(); var btn = $('scrollToBottomBtn'); if (btn) btn.hidden = !_userScrolledUp; });
var stbb = $('scrollToBottomBtn'); if (stbb) stbb.addEventListener('click', function() { _userScrolledUp = false; chat.scrollTop = chat.scrollHeight; stbb.hidden = true; });

/* ─── P1-5: 消息操作 ─── */
function addMsgActions(el, role, rawText) { var actions = document.createElement('div'); actions.className = 'msg-actions'; var cbtn = document.createElement('button'); cbtn.className = 'msg-act-btn'; cbtn.textContent = 'copy'; cbtn.onclick = function(e) { e.stopPropagation(); var b = el.querySelector('.bubble'); navigator.clipboard.writeText(b ? b.textContent : rawText || '').then(function() { cbtn.textContent = 'ok'; setTimeout(function() { cbtn.textContent = 'copy'; }, 1200); }); }; actions.appendChild(cbtn); if (role === 'user') { var ebtn = document.createElement('button'); ebtn.className = 'msg-act-btn'; ebtn.textContent = 'edit'; ebtn.onclick = function(e) { e.stopPropagation(); input.value = rawText || (el.querySelector('.bubble') ? el.querySelector('.bubble').textContent : ''); autosize(); input.focus(); }; actions.appendChild(ebtn); } var dbtn = document.createElement('button'); dbtn.className = 'msg-act-btn'; dbtn.textContent = 'del'; dbtn.onclick = function(e) { e.stopPropagation(); el.remove(); }; actions.appendChild(dbtn); el.appendChild(actions); }

/* ─── P1-1: 可折叠工具 ─── */
function appendActivity(ev) { if (!activeAssistEl) return; if (!activeActsEl) { activeActsEl = document.createElement('div'); activeActsEl.className = 'acts'; activeAssistEl.appendChild(activeActsEl); } var labelMap = { tool_start: 'TOOL', tool_end: 'DONE', tool_error: 'ERR', thought: 'THINK', info: 'INFO' }; var label = labelMap[ev.type] || 'INFO', tagClass = 'tag tag-' + (ev.type || 'info'); var d = document.createElement('details'); d.className = 'tool-call act act-' + (ev.type || 'info'); d.innerHTML = '<summary><span class="' + tagClass + '">' + label + '</span><span>' + escapeHtml(ev.message) + '</span></summary>'; if (ev.detail) { var body = document.createElement('div'); body.className = 'tool-body'; body.textContent = typeof ev.detail === 'string' ? ev.detail : JSON.stringify(ev.detail, null, 2); d.appendChild(body); } activeActsEl.appendChild(d); scrollDown(); }

/* ─── 消息渲染 ─── */
function addMsg(role, text) { var el = document.createElement('div'); el.className = 'msg ' + role; var label = { user: '\u4f60', assistant: '\u52a9\u624b', system: '\u7cfb\u7edf' }[role] || role; el.setAttribute('aria-label', label + '\u6d88\u606f'); if (role === 'assistant' && !text) { el.innerHTML = '<div class="who">' + label + '</div><div class="bubble"><div class="typing-indicator"><span></span><span></span><span></span></div></div>'; } else { el.innerHTML = '<div class="who">' + label + '</div><div class="bubble"></div>'; el.querySelector('.bubble').innerHTML = renderMarkdownFull(text); enhanceCodeBlocks(el.querySelector('.bubble')); } chat.appendChild(el); addMsgActions(el, role, text); scrollDown(true); return el; }
function removeTypingIndicator(el) { if (!el) return; var ind = el.querySelector('.typing-indicator'); if (ind) ind.remove(); }
function appendThought(text) { if (!activeAssistEl) return; if (!activeThoughtEl) { activeThoughtEl = document.createElement('div'); activeThoughtEl.className = 'thought'; activeThoughtEl.innerHTML = '<span class="thought-label">\u601d\u8003</span><span class="thought-text"></span>'; activeAssistEl.insertBefore(activeThoughtEl, activeAssistEl.querySelector('.bubble')); } activeThoughtEl.querySelector('.thought-text').textContent += text; scrollDown(); }

/* ─── WebSocket ─── */
var _wasDisconnected = false;
function connect() { var proto = location.protocol === 'https:' ? 'wss' : 'ws'; ws = new WebSocket(proto + '://' + location.host + '/ws'); ws.onopen = function() { setConn('\u5df2\u8fde\u63a5', 'ok'); if (_wasDisconnected) { showToast('\u5df2\u91cd\u65b0\u8fde\u63a5', 'success'); _wasDisconnected = false; } }; ws.onclose = function() { setConn('\u65ad\u5f00\uff0c\u91cd\u8fde\u4e2d\u2026', 'bad'); if (!_wasDisconnected) { showToast('\u8fde\u63a5\u5df2\u65ad\u5f00\uff0c\u6b63\u5728\u91cd\u8fde\u2026', 'warning'); _wasDisconnected = true; } setTimeout(connect, 2000); }; ws.onmessage = function(e) { var m; try { m = JSON.parse(e.data); } catch { return; } if (m.type === 'ready') { setConn('\u5df2\u8fde\u63a5 \u00b7 ' + m.provider, 'ok'); if (_wasDisconnected) { showToast('\u5df2\u91cd\u65b0\u8fde\u63a5', 'success'); _wasDisconnected = false; } } else if (m.type === 'token') { if (activeAssistEl) { removeTypingIndicator(activeAssistEl); var bub = activeAssistEl.querySelector('.bubble'); bub.innerHTML += renderMarkdown(m.text); bub.classList.add('streaming'); setTimeout(function() { bub.classList.remove('streaming'); }, 600); enhanceCodeBlocks(bub); scrollDown(); } } else if (m.type === 'thought') { if (activeAssistEl) appendThought(m.text); } else if (m.type === 'activity') appendActivity(m.ev); else if (m.type === 'done') { if (activeAssistEl && m.content) { removeTypingIndicator(activeAssistEl); var bub = activeAssistEl.querySelector('.bubble'); bub.innerHTML = renderMarkdownFull(m.content); enhanceCodeBlocks(bub); } finishTurn(); } else if (m.type === 'error') { addMsg('system', '\u9519\u8bef: ' + m.message); finishTurn(); } else if (m.type === 'busy') addMsg('system', m.message); }; }
function setConn(text, cls) { var c = $('conn'); c.textContent = text; c.className = 'conn ' + (cls || ''); }
function setBusy(b) { busy = b; sendBtn.classList.toggle('stop', b); var si = sendBtn.querySelector('.send-icon'); if (si) si.textContent = b ? '\u25a0' : '\u2191'; sendBtn.title = b ? '\u505c\u6b62' : '\u53d1\u9001'; }
function finishTurn() { activeAssistEl = null; activeActsEl = null; activeThoughtEl = null; setBusy(false); refreshTokens(); }

/* ─── P1-6: 导出 ─── */
function exportChat() { var msgs = chat.querySelectorAll('.msg'); if (!msgs.length) { showToast('\u6ca1\u6709\u53ef\u5bfc\u51fa\u7684\u6d88\u606f', 'warning'); return; } var md = '# AGENT HARNESS Chat\n\n> ' + new Date().toLocaleString('zh-CN') + '\n> Session: ' + sessionId + '\n\n---\n\n'; for (var i = 0; i < msgs.length; i++) { var m = msgs[i]; var role = m.classList.contains('user') ? '**User**' : m.classList.contains('assistant') ? '**AI**' : '**System**'; md += '### ' + role + '\n\n' + (m.querySelector('.bubble') ? m.querySelector('.bubble').textContent : '') + '\n\n'; } var blob = new Blob([md], { type: 'text/markdown' }); var url = URL.createObjectURL(blob); var a = document.createElement('a'); a.href = url; a.download = 'chat_' + new Date().toISOString().slice(0, 10) + '.md'; a.click(); URL.revokeObjectURL(url); showToast('\u5bfc\u51fa\u5b8c\u6210', 'success'); }
$('exportBtn').onclick = exportChat;

/* ─── 发送 ─── */
function send(content) { if (busy || (!content.trim() && !pendingAttachments.length)) return; var es = $('emptyState'); if (es) es.remove(); setBusy(true); var userEl = addMsg('user', content); renderAttachInBubble(userEl, pendingAttachments); _userScrolledUp = false; activeAssistEl = addMsg('assistant', ''); activeActsEl = null; ws.send(JSON.stringify({ type: 'chat', content: content, sessionId: sessionId, modelId: currentModelId || undefined, attachments: pendingAttachments.map(function(a) { return { name: a.name, path: a.path, size: a.size, mime: a.mime, text: a.text }; }) })); pendingAttachments = []; renderAttachArea(); updateCtxBadge(0); }
function sendStop() { if (ws && ws.readyState === 1) ws.send(JSON.stringify({ type: 'stop' })); }
sendBtn.onclick = function() { if (busy) sendStop(); else { var v = input.value; input.value = ''; autosize(); send(v); } };
document.addEventListener('keydown', function(e) { if ((e.ctrlKey || e.metaKey) && (e.key === 'k' || e.key === 'n')) { e.preventDefault(); newChat(); } if (e.key === 'Escape' && busy) { e.preventDefault(); sendStop(); } if (e.key === 'Escape' && !busy) $('modelDropdown').hidden = true; });
input.addEventListener('keydown', function(e) { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); var v = input.value; input.value = ''; autosize(); send(v); } });
input.addEventListener('input', function() { autosize(); updateCtxBadge(estimateTokensJS(input.value)); updateInputTokens(); });
function autosize() { input.style.height = 'auto'; input.style.height = Math.min(input.scrollHeight, 160) + 'px'; }

/* ─── 文件上传 (P1-9: 进度条) ─── */
var MAX_UPLOAD = 500 * 1024 * 1024;
var TEXT_EXT = new Set(['txt','md','markdown','json','csv','tsv','xml','log','yaml','yml','ini','toml','html','htm','css','js','jsx','ts','tsx','py','java','c','cpp','h','hpp','go','rs','sh','bat','ps1','sql','tex','r','rb','php','vue','gitignore']);
function isTextFile(name) { return TEXT_EXT.has((name.split('.').pop() || '').toLowerCase()); }
function fmtBytes(b) { if (b >= 1048576) return (b / 1048576).toFixed(1) + 'MB'; if (b >= 1024) return (b / 1024).toFixed(0) + 'KB'; return b + 'B'; }

function renderAttachArea() { var area = $('attachArea'); if (!area) return; area.innerHTML = ''; for (var i = 0; i < pendingAttachments.length; i++) { (function(idx) { var a = pendingAttachments[idx]; var chip = document.createElement('span'); chip.className = 'chip'; chip.innerHTML = '<span class="chip-ico">' + (a.kind || 'file') + '</span><span class="chip-name">' + escapeHtml(a.name) + '</span><span class="chip-size">' + fmtBytes(a.size) + '</span><span class="chip-x">X</span>'; chip.querySelector('.chip-x').onclick = function() { pendingAttachments.splice(idx, 1); renderAttachArea(); }; area.appendChild(chip); })(i); } }
function uploadFileWithProgress(file, onProgress, onDone) { var xhr = new XMLHttpRequest(), fd = new FormData(); fd.append('file', file, file.name); fd.append('sessionId', sessionId); xhr.open('POST', '/api/upload'); xhr.upload.onprogress = function(e) { if (e.lengthComputable && onProgress) onProgress(e.loaded, e.total); }; xhr.onload = function() { try { onDone(null, JSON.parse(xhr.responseText)); } catch (err) { onDone(err); } }; xhr.onerror = function() { onDone(new Error('Network error')); }; xhr.send(fd); return xhr; }

async function handleFiles(fileList) { for (var i = 0; i < fileList.length; i++) { (function(file) { if (file.size > MAX_UPLOAD) { showToast('\u8d85\u8fc7500MB: ' + file.name, 'warning'); return; } var text = undefined, tp = Promise.resolve(); if (isTextFile(file.name) && file.size <= 200*1024) { tp = file.text().then(function(t) { text = t.length > 120000 ? t.slice(0, 120000) + '\n...(truncated)' : t; }).catch(function() {}); } var area = $('attachArea'); var prog = document.createElement('div'); prog.className = 'upload-progress'; prog.innerHTML = '<span class="up-name">' + escapeHtml(file.name) + '</span><span class="up-bar"><span class="up-bar-fill" style="width:0%"></span></span><span class="up-pct">0%</span><button class="up-cancel">X</button>'; area.appendChild(prog); var cancelled = false; prog.querySelector('.up-cancel').onclick = function() { cancelled = true; xhr.abort(); prog.remove(); }; var xhr = uploadFileWithProgress(file, function(loaded,total) { var pct = Math.round(loaded/total*100); prog.querySelector('.up-bar-fill').style.width = pct + '%'; prog.querySelector('.up-pct').textContent = pct + '%'; }, function(err,d) { prog.remove(); if (cancelled) return; if (err||!d||!d.ok) { showToast('\u4e0a\u4f20\u5931\u8d25: ' + (d&&d.error?d.error:file.name), 'error'); return; } tp.then(function() { pendingAttachments.push({ name:d.name, path:d.path, size:d.size, mime:d.mime, kind:d.kind, text:text }); renderAttachArea(); }); }); })(fileList[i]); } }

$('attachBtn').onclick = function() { $('fileInput').click(); };
$('fileInput').onchange = function(e) { handleFiles(e.target.files); e.target.value = ''; };
var chatEl = $('chat');
['dragenter', 'dragover'].forEach(function(ev) { chatEl.addEventListener(ev, function(e) { e.preventDefault(); $('dropOverlay').hidden = false; }); });
chatEl.addEventListener('dragleave', function(e) { if (e.target === chatEl) $('dropOverlay').hidden = true; });
chatEl.addEventListener('drop', function(e) { e.preventDefault(); $('dropOverlay').hidden = true; if (e.dataTransfer && e.dataTransfer.files && e.dataTransfer.files.length) handleFiles(e.dataTransfer.files); });
function renderAttachInBubble(el, list) { if (!list || !list.length) return; var wrap = document.createElement('div'); wrap.className = 'attach-in-msg'; for (var i = 0; i < list.length; i++) { var a = list[i]; var chip = document.createElement('span'); chip.className = 'chip'; chip.innerHTML = '<span class="chip-ico">' + (a.kind||'file') + '</span><span class="chip-name">' + escapeHtml(a.name) + '</span><span class="chip-size">' + fmtBytes(a.size) + '</span>'; wrap.appendChild(chip); } el.querySelector('.bubble').appendChild(wrap); }

/* ─── 模型选择器 ─── */
function loadModels() { return fetch('/api/models').then(function(r) { return r.json(); }).then(function(d) { modelGroups = d.groups || []; if (!currentModelId && d.activeModelId) currentModelId = d.activeModelId; if (!currentModelId && modelGroups[0] && modelGroups[0].models[0]) currentModelId = modelGroups[0].models[0].id; renderModelGroups(''); updateModelTrigger(); var footModel = $('footModel'); if (footModel) footModel.textContent = labelOf(currentModelId) || '\u2014'; }); }
function labelOf(id) { for (var i = 0; i < modelGroups.length; i++) { var m = modelGroups[i].models.find(function(x) { return x.id === id; }); if (m) return m.label; } return null; }
function renderModelGroups(filter) { var wrap = $('modelGroups'); wrap.innerHTML = ''; var f = filter.trim().toLowerCase(); for (var i = 0; i < modelGroups.length; i++) { var g = modelGroups[i]; var items = g.models.filter(function(m) { return !f || m.label.toLowerCase().includes(f); }); if (!items.length) continue; var gl = document.createElement('div'); gl.className = 'model-group-label'; gl.textContent = g.label; wrap.appendChild(gl); for (var j = 0; j < items.length; j++) { var m = items[j]; var it = document.createElement('div'); it.className = 'model-item' + (m.id === currentModelId ? ' selected' : ''); it.setAttribute('role', 'option'); it.setAttribute('aria-selected', m.id === currentModelId ? 'true' : 'false'); it.innerHTML = '<span class="mi-dot"></span><span>' + escapeHtml(m.label) + '</span>'; it.onclick = (function(id) { return function() { selectModel(id); }; })(m.id); wrap.appendChild(it); } } }
function selectModel(id) { currentModelId = id; updateModelTrigger(); $('modelDropdown').hidden = true; var lbl = labelOf(id); if (lbl) setConn('\u5df2\u8fde\u63a5 \u00b7 ' + lbl, 'ok'); var fm = $('footModel'); if (fm) fm.textContent = lbl || '\u2014'; fetch('/api/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ activeModelId: id }) }).catch(function() {}); }
function updateModelTrigger() { $('modelName').textContent = labelOf(currentModelId) || '\u9009\u62e9\u6a21\u578b\u2026'; }
$('modelTrigger').onclick = function(e) { e.stopPropagation(); var d = $('modelDropdown'); d.hidden = !d.hidden; if (!d.hidden) $('modelSearch').focus(); };
$('modelSearch').oninput = function(e) { renderModelGroups(e.target.value); };
document.addEventListener('click', function(e) { if (!$('modelSelect').contains(e.target)) $('modelDropdown').hidden = true; });
$('modelSettingsLink').onclick = function() { $('modelDropdown').hidden = true; switchView('settings'); };

/* ─── 新建对话 ─── */
function newChat() { sessionId = 'sess_' + Date.now(); localStorage.setItem('ah_session', sessionId); chat.innerHTML = ''; var es = document.createElement('div'); es.className = 'empty'; es.id = 'emptyState'; es.innerHTML = '<div class="empty-logo">\u25c6</div><h2>\u65b0\u5bf9\u8bdd</h2><p>\u6b22\u8fce\u4f7f\u7528 DaShaAgent</p><div class="prompt-chips"><div class="prompt-chip" data-prompt="\u4eca\u5929\u6709\u54ea\u4e9b\u91cd\u8981\u7684\u6d77\u4e8b\u65b0\u95fb\uff1f">\u6d77\u4e8b\u65b0\u95fb</div><div class="prompt-chip" data-prompt="\u5e2e\u6211\u5199\u4e00\u4e2a Python \u811a\u672c">Python \u811a\u672c</div><div class="prompt-chip" data-prompt="\u603b\u7ed3\u5f53\u524d\u9879\u76ee\u7684\u6838\u5fc3\u529f\u80fd">\u9879\u76ee\u603b\u7ed3</div><div class="prompt-chip" data-prompt="\u89e3\u91ca\u4e00\u4e0b AI Agent \u7684\u5de5\u4f5c\u539f\u7406">AI Agent</div></div>'; chat.appendChild(es); currentTokens = 0; updateCtxBadge(0); showToast('\u5df2\u521b\u5efa\u65b0\u5bf9\u8bdd', 'success'); setTimeout(function() { document.querySelectorAll('.prompt-chip').forEach(function(c) { c.onclick = function() { input.value = this.dataset.prompt; autosize(); send(input.value); }; }); }, 100); return es; }

$('newChatBtn').onclick = function() { newChat(); };
$('compressBtn').onclick = function() { if (ws && ws.readyState === 1) ws.send(JSON.stringify({ type: 'compress', sessionId: sessionId })); showToast('\u538b\u7f29\u4e0a\u4e0b\u6587\u4e2d\u2026'); };
$('teamBtn').onclick = function() { var task = prompt('\u591a\u667a\u80fd\u4f53\u4efb\u52a1:'); if (!task) return; addMsg('system', '\u542f\u52a8\u591a\u667a\u80fd\u4f53\u4efb\u52a1: ' + task); ws.send(JSON.stringify({ type: 'team', task: task, sessionId: sessionId })); showToast('\u5df2\u542f\u52a8\u591a\u667a\u80fd\u4f53\u4efb\u52a1'); };
$('jobBtn').onclick = function() { addMsg('system', '\u6267\u884c\u6bcf\u65e5\u7b80\u62a5\u2026'); ws.send(JSON.stringify({ type: 'job', name: 'daily_brief', sessionId: sessionId })); showToast('\u5df2\u542f\u52a8\u6bcf\u65e5\u7b80\u62a5'); };
